server:
  port: 9000

spring:
  security:
    user:
      name: user
      password: user
  datasource:
    url: jdbc:postgresql://localhost:5332/wsda
    username: admin
    password: admin
  base: 'http://localhost:9000/'

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet