server:
  port: 9000

spring:
  security:
    user:
      name: user
      password: user
  datasource:
    url: jdbc:mysql://localhost:3306/muzio
    username: root
    password: ''
  base: 'http://localhost:9000/'

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet

logging:
  level:
    org:
      springframework:
        security: DEBUG